### ISSUE TITLE
Unable to install on 8.6.3

### ISSUE THREAD

**Issue by prosperva** [YourITGroup/ConfigurationEditor#1]
I am getting an error trying to install this pachage

Server error: Contact administrator, see log for full details.
Failed to get package details

Nothing in the log files.

**Comment by robertjf** [comment]
Hi, can you give some more details?  How are you trying to install, what version of Umbraco, some screen shots may be helpful?

**Comment by robertjf** [comment]
Sorry, just noticed you mentioned 8.6.3 in the title - the project may not support that version of Umbraco, can you upgrade to at least 8.6.4 and try again?
